// <auto-generated />
using System;
using MSP.Infrastructure.Persistence.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MSP.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110174103_RenameTaskReassignToTaskHistory")]
    partial class RenameTaskReassignToTaskHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MSP.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Limitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUnlimited")
                        .HasColumnType("boolean");

                    b.Property<string>("LimitUnit")
                        .HasColumnType("text");

                    b.Property<int?>("LimitValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Limitations");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecordUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transcription")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MSP.Domain.Entities.OrganizationInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessOwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("BusinessOwnerId", "Status");

                    b.HasIndex("MemberId", "Status");

                    b.ToTable("OrganizationInvitations");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MSP.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("MSP.Domain.Entities.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TodoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TodoId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("TransactionID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("MSP.Domain.Entities.TaskHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FromUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("TaskId");

                    b.HasIndex("ToUserId");

                    b.ToTable("TaskHistories");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("UserId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("MSP.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("BusinessLicense")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ManagedById")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedById");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-4789-1234-56789abcdef2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f35d3654-6277-4ab5-a445-80f9d485ae74",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Nguyen Van An",
                            IsActive = true,
                            IsApproved = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAECdSBsuSNxcNI/kgAlbEtx2m2MrB7Bbl+ZOfQ/GhQrZnWo3GyZllpmeLduoEPeIDRw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c6a3df81-ae91-45ad-a3e9-ba69c044740f",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("c2d4e3f4-a5b6-4789-1234-56789abcdef2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "88558d9a-de3e-4429-a64a-03e76291a713",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member1@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Le Thi Thuy",
                            IsActive = true,
                            IsApproved = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER1@GMAIL.COM",
                            NormalizedUserName = "MEMBER",
                            PasswordHash = "AQAAAAIAAYagAAAAEP3BphC3V1uYgHvt4/cS0oGGjR8E/SQY9ClsLXN2l1FO/Fumx8FH6XN/OnF+0tRWfg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0f1541d3-dfaa-46ac-a5cf-f401154036f7",
                            TwoFactorEnabled = false,
                            UserName = "Member"
                        },
                        new
                        {
                            Id = new Guid("d2a5b3c4-d7e8-4789-1234-56789abcdef3"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "99d9689d-0127-4a87-9ca3-aad136355d55",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member2@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Pham Minh Hieu",
                            IsActive = true,
                            IsApproved = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER2@GMAIL.COM",
                            NormalizedUserName = "MEMBER2",
                            PasswordHash = "AQAAAAIAAYagAAAAELG8FWYYYRv4Vb5jsObE+JMpjYViNT+OJZj96o2YBeqSfAYgJQTggM099LrO+qNa/g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c76ecc82-26c6-485f-a699-1c3a28907c25",
                            TwoFactorEnabled = false,
                            UserName = "Member2"
                        },
                        new
                        {
                            Id = new Guid("e3b6c7d8-a9f0-4789-1234-56789abcdef4"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "73ba14b0-4110-4070-bf5c-a2e852169cf6",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member3@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Nguyen Bao Chau",
                            IsActive = true,
                            IsApproved = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER3@GMAIL.COM",
                            NormalizedUserName = "MEMBER3",
                            PasswordHash = "AQAAAAIAAYagAAAAEPBohWsnnVj0a0KUlC6ffNqDockOtP+aTCzi1oHSqlJ7U6AYI9POO9DPZSHwjofP4Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "88f98561-9418-4bab-87c9-f5f22ad42c29",
                            TwoFactorEnabled = false,
                            UserName = "Member3"
                        },
                        new
                        {
                            Id = new Guid("f4c7d8e9-b1a2-4789-1234-56789abcdef5"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "65f62f71-7dcb-429c-a60c-db1f0962a1a1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member4@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Do Thi Lan Anh",
                            IsActive = true,
                            IsApproved = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER4@GMAIL.COM",
                            NormalizedUserName = "MEMBER4",
                            PasswordHash = "AQAAAAIAAYagAAAAEL9qQmmzPdVZBlJY16ebGAM08ji3GZZzL465uwm5I2RIKHe+4x8Sb7jw+ZdvWeCQng==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e9d40e22-396b-4714-b1fa-5cb1d545ef96",
                            TwoFactorEnabled = false,
                            UserName = "Member4"
                        },
                        new
                        {
                            Id = new Guid("c3d4e3f4-a5b6-4789-1234-56789abcdef2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6d3a3071-8afa-49e9-9570-65b89c2fba52",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pm@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Tran Van Binh",
                            IsActive = true,
                            IsApproved = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PM@GMAIL.COM",
                            NormalizedUserName = "PROJECTMANAGER",
                            PasswordHash = "AQAAAAIAAYagAAAAEPHWg7jv9W7OWXjk5RaITR++YWG1hTbbAlIq2OZ01Cgjm7pK+6oFx6YV6AwZRJ+JzA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "803354f8-bb58-40e3-80db-61c577d8ee72",
                            TwoFactorEnabled = false,
                            UserName = "ProjectManager"
                        },
                        new
                        {
                            Id = new Guid("c4d4e3f4-a5b6-4789-1234-56789abcdef2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "90d5347e-118d-4e78-b19b-5362af246dba",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bo1@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Ngo Van Thanh",
                            IsActive = true,
                            IsApproved = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BO1@GMAIL.COM",
                            NormalizedUserName = "BUSINESSOWNER",
                            Organization = "FPT Software",
                            PasswordHash = "AQAAAAIAAYagAAAAEKtF1ZvRoWtx8rBvPHUAaDk+JLcBLNsgn+f9eitLH2fgER0AujmkmcKmeU+RwTk8pA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ea8061c5-9e3b-410f-bea0-1d03ac1f8c5e",
                            TwoFactorEnabled = false,
                            UserName = "BusinessOwner"
                        },
                        new
                        {
                            Id = new Guid("a5b6c7d8-e9f0-4789-1234-56789abcdef6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4820fe9c-871e-4d28-adba-0e86e86e08c3",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bo2@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Hoang Thi Hong",
                            IsActive = true,
                            IsApproved = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BO2@GMAIL.COM",
                            NormalizedUserName = "BUSINESSOWNER2",
                            Organization = "VNPT Technology",
                            PasswordHash = "AQAAAAIAAYagAAAAEFyXJbLzkK8A7E8H2fjDVaHCh8vEVnVnyNhDlERHZVYqZZ8oiHzyBC8IJGTM1vsz2w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ad811c79-f10e-40de-887b-53059ae5090b",
                            TwoFactorEnabled = false,
                            UserName = "BusinessOwner2"
                        },
                        new
                        {
                            Id = new Guid("b6c7d8e9-f0a1-4789-1234-56789abcdef7"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "36b49e05-46fb-40fb-b035-6041e77b53c1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bo3@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Le Van Phuc",
                            IsActive = true,
                            IsApproved = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BO3@GMAIL.COM",
                            NormalizedUserName = "BUSINESSOWNER3",
                            Organization = "CMC Corporation",
                            PasswordHash = "AQAAAAIAAYagAAAAED6QqnHjYwpYUzZAoUAWFoiTGiFYwAdmWrp1q5L/re1mtjxYx4z0dRCykCdmG5bkDg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "64831ea2-a171-426e-b4d3-119d4188b475",
                            TwoFactorEnabled = false,
                            UserName = "BusinessOwner3"
                        });
                });

            modelBuilder.Entity("MeetingUser", b =>
                {
                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("MeetingId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MeetingUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-1234-56789abcdef0"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-4789-1234-56789abcdef1"),
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-4789-1234-56789abcdef2"),
                            Name = "ProjectManager",
                            NormalizedName = "PROJECTMANAGER"
                        },
                        new
                        {
                            Id = new Guid("d1e2f3a4-b5c6-4789-1234-56789abcdef3"),
                            Name = "BusinessOwner",
                            NormalizedName = "BUSINESSOWNER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c1d2e3f4-a5b6-4789-1234-56789abcdef2"),
                            RoleId = new Guid("a1b2c3d4-e5f6-4789-1234-56789abcdef0")
                        },
                        new
                        {
                            UserId = new Guid("c2d4e3f4-a5b6-4789-1234-56789abcdef2"),
                            RoleId = new Guid("b1c2d3e4-f5a6-4789-1234-56789abcdef1")
                        },
                        new
                        {
                            UserId = new Guid("d2a5b3c4-d7e8-4789-1234-56789abcdef3"),
                            RoleId = new Guid("b1c2d3e4-f5a6-4789-1234-56789abcdef1")
                        },
                        new
                        {
                            UserId = new Guid("e3b6c7d8-a9f0-4789-1234-56789abcdef4"),
                            RoleId = new Guid("b1c2d3e4-f5a6-4789-1234-56789abcdef1")
                        },
                        new
                        {
                            UserId = new Guid("f4c7d8e9-b1a2-4789-1234-56789abcdef5"),
                            RoleId = new Guid("b1c2d3e4-f5a6-4789-1234-56789abcdef1")
                        },
                        new
                        {
                            UserId = new Guid("c3d4e3f4-a5b6-4789-1234-56789abcdef2"),
                            RoleId = new Guid("c1d2e3f4-a5b6-4789-1234-56789abcdef2")
                        },
                        new
                        {
                            UserId = new Guid("c4d4e3f4-a5b6-4789-1234-56789abcdef2"),
                            RoleId = new Guid("d1e2f3a4-b5c6-4789-1234-56789abcdef3")
                        },
                        new
                        {
                            UserId = new Guid("a5b6c7d8-e9f0-4789-1234-56789abcdef6"),
                            RoleId = new Guid("d1e2f3a4-b5c6-4789-1234-56789abcdef3")
                        },
                        new
                        {
                            UserId = new Guid("b6c7d8e9-f0a1-4789-1234-56789abcdef7"),
                            RoleId = new Guid("d1e2f3a4-b5c6-4789-1234-56789abcdef3")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MilestoneTask", b =>
                {
                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("MilestoneId", "ProjectTaskId");

                    b.HasIndex("ProjectTaskId");

                    b.ToTable("MilestoneTasks", (string)null);
                });

            modelBuilder.Entity("PackageLimitation", b =>
                {
                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LimitationId")
                        .HasColumnType("uuid");

                    b.HasKey("PackageId", "LimitationId");

                    b.HasIndex("LimitationId");

                    b.ToTable("PackageLimitations", (string)null);
                });

            modelBuilder.Entity("ProjectTaskTodo", b =>
                {
                    b.Property<Guid>("ReferencedTasksId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferencingTodosId")
                        .HasColumnType("uuid");

                    b.HasKey("ReferencedTasksId", "ReferencingTodosId");

                    b.HasIndex("ReferencingTodosId");

                    b.ToTable("ProjectTaskTodo");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Comment", b =>
                {
                    b.HasOne("MSP.Domain.Entities.ProjectTask", "ProjectTask")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectTask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Document", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Meeting", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.Milestone", "Milestone")
                        .WithMany()
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MSP.Domain.Entities.Project", "Project")
                        .WithMany("Meetings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Milestone");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Milestone", b =>
                {
                    b.HasOne("MSP.Domain.Entities.Project", "Project")
                        .WithMany("Milestones")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MSP.Domain.Entities.OrganizationInvitation", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "BusinessOwner")
                        .WithMany("OrganizationInvitationsAsOwner")
                        .HasForeignKey("BusinessOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "Member")
                        .WithMany("OrganizationInvitationsAsMember")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessOwner");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Package", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Project", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MSP.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MSP.Domain.Entities.ProjectTask", b =>
                {
                    b.HasOne("MSP.Domain.Entities.Project", "Project")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.Todo", "Todo")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MSP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Project");

                    b.Navigation("Todo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("MSP.Domain.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MSP.Domain.Entities.TaskHistory", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MSP.Domain.Entities.ProjectTask", "Task")
                        .WithMany("TaskHistories")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("Task");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Todo", b =>
                {
                    b.HasOne("MSP.Domain.Entities.Meeting", "Meeting")
                        .WithMany("Todos")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Meeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MSP.Domain.Entities.User", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", "ManagedBy")
                        .WithMany("ManagedUsers")
                        .HasForeignKey("ManagedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ManagedBy");
                });

            modelBuilder.Entity("MeetingUser", b =>
                {
                    b.HasOne("MSP.Domain.Entities.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MSP.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MilestoneTask", b =>
                {
                    b.HasOne("MSP.Domain.Entities.Milestone", null)
                        .WithMany()
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.ProjectTask", null)
                        .WithMany()
                        .HasForeignKey("ProjectTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PackageLimitation", b =>
                {
                    b.HasOne("MSP.Domain.Entities.Limitation", null)
                        .WithMany()
                        .HasForeignKey("LimitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectTaskTodo", b =>
                {
                    b.HasOne("MSP.Domain.Entities.ProjectTask", null)
                        .WithMany()
                        .HasForeignKey("ReferencedTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSP.Domain.Entities.Todo", null)
                        .WithMany()
                        .HasForeignKey("ReferencingTodosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MSP.Domain.Entities.Meeting", b =>
                {
                    b.Navigation("Todos");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Project", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Meetings");

                    b.Navigation("Milestones");

                    b.Navigation("ProjectMembers");

                    b.Navigation("ProjectTasks");
                });

            modelBuilder.Entity("MSP.Domain.Entities.ProjectTask", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("TaskHistories");
                });

            modelBuilder.Entity("MSP.Domain.Entities.Todo", b =>
                {
                    b.Navigation("ProjectTasks");
                });

            modelBuilder.Entity("MSP.Domain.Entities.User", b =>
                {
                    b.Navigation("ManagedUsers");

                    b.Navigation("Notifications");

                    b.Navigation("OrganizationInvitationsAsMember");

                    b.Navigation("OrganizationInvitationsAsOwner");
                });
#pragma warning restore 612, 618
        }
    }
}
